# Generated by Django 2.2.2 on 2019-06-09 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_auto_20190609_1107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='card',
            name='suit',
        ),
    ]
